<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib\Models;

class CERRARRETIROREQUEST implements \JsonSerializable
{
    /**
     * @var string
     */
    private $idValidator;

    /**
     * @var string
     */
    private $nameValidator;

    /**
     * @var string
     */
    private $dateClosed;

    /**
     * @var string
     */
    private $state;

    /**
     * @param string $idValidator
     * @param string $nameValidator
     * @param string $dateClosed
     * @param string $state
     */
    public function __construct(string $idValidator, string $nameValidator, string $dateClosed, string $state)
    {
        $this->idValidator = $idValidator;
        $this->nameValidator = $nameValidator;
        $this->dateClosed = $dateClosed;
        $this->state = $state;
    }

    /**
     * Returns Id Validator.
     */
    public function getIdValidator(): string
    {
        return $this->idValidator;
    }

    /**
     * Sets Id Validator.
     *
     * @required
     * @maps id_validator
     */
    public function setIdValidator(string $idValidator): void
    {
        $this->idValidator = $idValidator;
    }

    /**
     * Returns Name Validator.
     */
    public function getNameValidator(): string
    {
        return $this->nameValidator;
    }

    /**
     * Sets Name Validator.
     *
     * @required
     * @maps name_validator
     */
    public function setNameValidator(string $nameValidator): void
    {
        $this->nameValidator = $nameValidator;
    }

    /**
     * Returns Date Closed.
     */
    public function getDateClosed(): string
    {
        return $this->dateClosed;
    }

    /**
     * Sets Date Closed.
     *
     * @required
     * @maps date_closed
     */
    public function setDateClosed(string $dateClosed): void
    {
        $this->dateClosed = $dateClosed;
    }

    /**
     * Returns State.
     */
    public function getState(): string
    {
        return $this->state;
    }

    /**
     * Sets State.
     *
     * @required
     * @maps state
     */
    public function setState(string $state): void
    {
        $this->state = $state;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['id_validator']   = $this->idValidator;
        $json['name_validator'] = $this->nameValidator;
        $json['date_closed']    = $this->dateClosed;
        $json['state']          = $this->state;

        return $json;
    }
}
