<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib\Models;

class CrearOrdenesRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $referenceNumber;

    /**
     * @var string
     */
    private $customerEmail;

    /**
     * @var string
     */
    private $tags;

    /**
     * @var Address
     */
    private $address;

    /**
     * @var Order
     */
    private $order;

    /**
     * @param string $referenceNumber
     * @param string $customerEmail
     * @param string $tags
     * @param Address $address
     * @param Order $order
     */
    public function __construct(
        string $referenceNumber,
        string $customerEmail,
        string $tags,
        Address $address,
        Order $order
    ) {
        $this->referenceNumber = $referenceNumber;
        $this->customerEmail = $customerEmail;
        $this->tags = $tags;
        $this->address = $address;
        $this->order = $order;
    }

    /**
     * Returns Reference Number.
     */
    public function getReferenceNumber(): string
    {
        return $this->referenceNumber;
    }

    /**
     * Sets Reference Number.
     *
     * @required
     * @maps reference_number
     */
    public function setReferenceNumber(string $referenceNumber): void
    {
        $this->referenceNumber = $referenceNumber;
    }

    /**
     * Returns Customer Email.
     */
    public function getCustomerEmail(): string
    {
        return $this->customerEmail;
    }

    /**
     * Sets Customer Email.
     *
     * @required
     * @maps customer_email
     */
    public function setCustomerEmail(string $customerEmail): void
    {
        $this->customerEmail = $customerEmail;
    }

    /**
     * Returns Tags.
     */
    public function getTags(): string
    {
        return $this->tags;
    }

    /**
     * Sets Tags.
     *
     * @required
     * @maps tags
     */
    public function setTags(string $tags): void
    {
        $this->tags = $tags;
    }

    /**
     * Returns Address.
     */
    public function getAddress(): Address
    {
        return $this->address;
    }

    /**
     * Sets Address.
     *
     * @required
     * @maps address
     */
    public function setAddress(Address $address): void
    {
        $this->address = $address;
    }

    /**
     * Returns Order.
     */
    public function getOrder(): Order
    {
        return $this->order;
    }

    /**
     * Sets Order.
     *
     * @required
     * @maps order
     */
    public function setOrder(Order $order): void
    {
        $this->order = $order;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['reference_number'] = $this->referenceNumber;
        $json['customer_email']   = $this->customerEmail;
        $json['tags']             = $this->tags;
        $json['address']          = $this->address;
        $json['order']            = $this->order;

        return $json;
    }
}
