<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib\Models;

class CREARCOMPLETEDEVREQUEST implements \JsonSerializable
{
    /**
     * @var int
     */
    private $idBusiness;

    /**
     * @var string
     */
    private $idWarehouse;

    /**
     * @var string
     */
    private $referenceNumber;

    /**
     * @var string
     */
    private $shopId;

    /**
     * @var string
     */
    private $customerIdentifier;

    /**
     * @var string
     */
    private $customerName;

    /**
     * @var string
     */
    private $customerEmail;

    /**
     * @var string
     */
    private $customerPhone;

    /**
     * @var Address1
     */
    private $address;

    /**
     * @var Order1
     */
    private $order;

    /**
     * @var string
     */
    private $deliveryType;

    /**
     * @var string
     */
    private $tags;

    /**
     * @param int $idBusiness
     * @param string $idWarehouse
     * @param string $referenceNumber
     * @param string $shopId
     * @param string $customerIdentifier
     * @param string $customerName
     * @param string $customerEmail
     * @param string $customerPhone
     * @param Address1 $address
     * @param Order1 $order
     * @param string $deliveryType
     * @param string $tags
     */
    public function __construct(
        int $idBusiness,
        string $idWarehouse,
        string $referenceNumber,
        string $shopId,
        string $customerIdentifier,
        string $customerName,
        string $customerEmail,
        string $customerPhone,
        Address1 $address,
        Order1 $order,
        string $deliveryType,
        string $tags
    ) {
        $this->idBusiness = $idBusiness;
        $this->idWarehouse = $idWarehouse;
        $this->referenceNumber = $referenceNumber;
        $this->shopId = $shopId;
        $this->customerIdentifier = $customerIdentifier;
        $this->customerName = $customerName;
        $this->customerEmail = $customerEmail;
        $this->customerPhone = $customerPhone;
        $this->address = $address;
        $this->order = $order;
        $this->deliveryType = $deliveryType;
        $this->tags = $tags;
    }

    /**
     * Returns Id Business.
     */
    public function getIdBusiness(): int
    {
        return $this->idBusiness;
    }

    /**
     * Sets Id Business.
     *
     * @required
     * @maps id_business
     */
    public function setIdBusiness(int $idBusiness): void
    {
        $this->idBusiness = $idBusiness;
    }

    /**
     * Returns Id Warehouse.
     */
    public function getIdWarehouse(): string
    {
        return $this->idWarehouse;
    }

    /**
     * Sets Id Warehouse.
     *
     * @required
     * @maps id_warehouse
     */
    public function setIdWarehouse(string $idWarehouse): void
    {
        $this->idWarehouse = $idWarehouse;
    }

    /**
     * Returns Reference Number.
     */
    public function getReferenceNumber(): string
    {
        return $this->referenceNumber;
    }

    /**
     * Sets Reference Number.
     *
     * @required
     * @maps reference_number
     */
    public function setReferenceNumber(string $referenceNumber): void
    {
        $this->referenceNumber = $referenceNumber;
    }

    /**
     * Returns Shop Id.
     */
    public function getShopId(): string
    {
        return $this->shopId;
    }

    /**
     * Sets Shop Id.
     *
     * @required
     * @maps shop_id
     */
    public function setShopId(string $shopId): void
    {
        $this->shopId = $shopId;
    }

    /**
     * Returns Customer Identifier.
     */
    public function getCustomerIdentifier(): string
    {
        return $this->customerIdentifier;
    }

    /**
     * Sets Customer Identifier.
     *
     * @required
     * @maps customer_identifier
     */
    public function setCustomerIdentifier(string $customerIdentifier): void
    {
        $this->customerIdentifier = $customerIdentifier;
    }

    /**
     * Returns Customer Name.
     */
    public function getCustomerName(): string
    {
        return $this->customerName;
    }

    /**
     * Sets Customer Name.
     *
     * @required
     * @maps customer_name
     */
    public function setCustomerName(string $customerName): void
    {
        $this->customerName = $customerName;
    }

    /**
     * Returns Customer Email.
     */
    public function getCustomerEmail(): string
    {
        return $this->customerEmail;
    }

    /**
     * Sets Customer Email.
     *
     * @required
     * @maps customer_email
     */
    public function setCustomerEmail(string $customerEmail): void
    {
        $this->customerEmail = $customerEmail;
    }

    /**
     * Returns Customer Phone.
     */
    public function getCustomerPhone(): string
    {
        return $this->customerPhone;
    }

    /**
     * Sets Customer Phone.
     *
     * @required
     * @maps customer_phone
     */
    public function setCustomerPhone(string $customerPhone): void
    {
        $this->customerPhone = $customerPhone;
    }

    /**
     * Returns Address.
     */
    public function getAddress(): Address1
    {
        return $this->address;
    }

    /**
     * Sets Address.
     *
     * @required
     * @maps address
     */
    public function setAddress(Address1 $address): void
    {
        $this->address = $address;
    }

    /**
     * Returns Order.
     */
    public function getOrder(): Order1
    {
        return $this->order;
    }

    /**
     * Sets Order.
     *
     * @required
     * @maps order
     */
    public function setOrder(Order1 $order): void
    {
        $this->order = $order;
    }

    /**
     * Returns Delivery Type.
     */
    public function getDeliveryType(): string
    {
        return $this->deliveryType;
    }

    /**
     * Sets Delivery Type.
     *
     * @required
     * @maps delivery_type
     */
    public function setDeliveryType(string $deliveryType): void
    {
        $this->deliveryType = $deliveryType;
    }

    /**
     * Returns Tags.
     */
    public function getTags(): string
    {
        return $this->tags;
    }

    /**
     * Sets Tags.
     *
     * @required
     * @maps tags
     */
    public function setTags(string $tags): void
    {
        $this->tags = $tags;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['id_business']         = $this->idBusiness;
        $json['id_warehouse']        = $this->idWarehouse;
        $json['reference_number']    = $this->referenceNumber;
        $json['shop_id']             = $this->shopId;
        $json['customer_identifier'] = $this->customerIdentifier;
        $json['customer_name']       = $this->customerName;
        $json['customer_email']      = $this->customerEmail;
        $json['customer_phone']      = $this->customerPhone;
        $json['address']             = $this->address;
        $json['order']               = $this->order;
        $json['delivery_type']       = $this->deliveryType;
        $json['tags']                = $this->tags;

        return $json;
    }
}
