<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib\Models;

class CREARRETIROCopyRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $idBusiness;

    /**
     * @var string
     */
    private $numOrder;

    /**
     * @var string
     */
    private $fullName;

    /**
     * @var string
     */
    private $email;

    /**
     * @var string
     */
    private $cellphone;

    /**
     * @var string
     */
    private $shippingType;

    /**
     * @var string
     */
    private $region;

    /**
     * @var string
     */
    private $comuna;

    /**
     * @var string
     */
    private $street;

    /**
     * @var string
     */
    private $reference;

    /**
     * @param string $idBusiness
     * @param string $numOrder
     * @param string $fullName
     * @param string $email
     * @param string $cellphone
     * @param string $shippingType
     * @param string $region
     * @param string $comuna
     * @param string $street
     * @param string $reference
     */
    public function __construct(
        string $idBusiness,
        string $numOrder,
        string $fullName,
        string $email,
        string $cellphone,
        string $shippingType,
        string $region,
        string $comuna,
        string $street,
        string $reference
    ) {
        $this->idBusiness = $idBusiness;
        $this->numOrder = $numOrder;
        $this->fullName = $fullName;
        $this->email = $email;
        $this->cellphone = $cellphone;
        $this->shippingType = $shippingType;
        $this->region = $region;
        $this->comuna = $comuna;
        $this->street = $street;
        $this->reference = $reference;
    }

    /**
     * Returns Id Business.
     */
    public function getIdBusiness(): string
    {
        return $this->idBusiness;
    }

    /**
     * Sets Id Business.
     *
     * @required
     * @maps id_business
     */
    public function setIdBusiness(string $idBusiness): void
    {
        $this->idBusiness = $idBusiness;
    }

    /**
     * Returns Num Order.
     */
    public function getNumOrder(): string
    {
        return $this->numOrder;
    }

    /**
     * Sets Num Order.
     *
     * @required
     * @maps num_order
     */
    public function setNumOrder(string $numOrder): void
    {
        $this->numOrder = $numOrder;
    }

    /**
     * Returns Full Name.
     */
    public function getFullName(): string
    {
        return $this->fullName;
    }

    /**
     * Sets Full Name.
     *
     * @required
     * @maps full_name
     */
    public function setFullName(string $fullName): void
    {
        $this->fullName = $fullName;
    }

    /**
     * Returns Email.
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     *
     * @required
     * @maps email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Cellphone.
     */
    public function getCellphone(): string
    {
        return $this->cellphone;
    }

    /**
     * Sets Cellphone.
     *
     * @required
     * @maps cellphone
     */
    public function setCellphone(string $cellphone): void
    {
        $this->cellphone = $cellphone;
    }

    /**
     * Returns Shipping Type.
     */
    public function getShippingType(): string
    {
        return $this->shippingType;
    }

    /**
     * Sets Shipping Type.
     *
     * @required
     * @maps shipping_type
     */
    public function setShippingType(string $shippingType): void
    {
        $this->shippingType = $shippingType;
    }

    /**
     * Returns Region.
     */
    public function getRegion(): string
    {
        return $this->region;
    }

    /**
     * Sets Region.
     *
     * @required
     * @maps region
     */
    public function setRegion(string $region): void
    {
        $this->region = $region;
    }

    /**
     * Returns Comuna.
     */
    public function getComuna(): string
    {
        return $this->comuna;
    }

    /**
     * Sets Comuna.
     *
     * @required
     * @maps comuna
     */
    public function setComuna(string $comuna): void
    {
        $this->comuna = $comuna;
    }

    /**
     * Returns Street.
     */
    public function getStreet(): string
    {
        return $this->street;
    }

    /**
     * Sets Street.
     *
     * @required
     * @maps street
     */
    public function setStreet(string $street): void
    {
        $this->street = $street;
    }

    /**
     * Returns Reference.
     */
    public function getReference(): string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     *
     * @required
     * @maps reference
     */
    public function setReference(string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['id_business']   = $this->idBusiness;
        $json['num_order']     = $this->numOrder;
        $json['full_name']     = $this->fullName;
        $json['email']         = $this->email;
        $json['cellphone']     = $this->cellphone;
        $json['shipping_type'] = $this->shippingType;
        $json['region']        = $this->region;
        $json['comuna']        = $this->comuna;
        $json['street']        = $this->street;
        $json['reference']     = $this->reference;

        return $json;
    }
}
