<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib\Models;

class CREARREQUEST implements \JsonSerializable
{
    /**
     * @var int
     */
    private $idBusiness;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $code;

    /**
     * @var string
     */
    private $adress;

    /**
     * @var string
     */
    private $adressNumber;

    /**
     * @var string
     */
    private $reference;

    /**
     * @var string
     */
    private $city;

    /**
     * @var string
     */
    private $region;

    /**
     * @param int $idBusiness
     * @param string $name
     * @param string $code
     * @param string $adress
     * @param string $adressNumber
     * @param string $reference
     * @param string $city
     * @param string $region
     */
    public function __construct(
        int $idBusiness,
        string $name,
        string $code,
        string $adress,
        string $adressNumber,
        string $reference,
        string $city,
        string $region
    ) {
        $this->idBusiness = $idBusiness;
        $this->name = $name;
        $this->code = $code;
        $this->adress = $adress;
        $this->adressNumber = $adressNumber;
        $this->reference = $reference;
        $this->city = $city;
        $this->region = $region;
    }

    /**
     * Returns Id Business.
     */
    public function getIdBusiness(): int
    {
        return $this->idBusiness;
    }

    /**
     * Sets Id Business.
     *
     * @required
     * @maps id_business
     */
    public function setIdBusiness(int $idBusiness): void
    {
        $this->idBusiness = $idBusiness;
    }

    /**
     * Returns Name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Code.
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * Sets Code.
     *
     * @required
     * @maps code
     */
    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    /**
     * Returns Adress.
     */
    public function getAdress(): string
    {
        return $this->adress;
    }

    /**
     * Sets Adress.
     *
     * @required
     * @maps adress
     */
    public function setAdress(string $adress): void
    {
        $this->adress = $adress;
    }

    /**
     * Returns Adress Number.
     */
    public function getAdressNumber(): string
    {
        return $this->adressNumber;
    }

    /**
     * Sets Adress Number.
     *
     * @required
     * @maps adress number
     */
    public function setAdressNumber(string $adressNumber): void
    {
        $this->adressNumber = $adressNumber;
    }

    /**
     * Returns Reference.
     */
    public function getReference(): string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     *
     * @required
     * @maps reference
     */
    public function setReference(string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns City.
     */
    public function getCity(): string
    {
        return $this->city;
    }

    /**
     * Sets City.
     *
     * @required
     * @maps city
     */
    public function setCity(string $city): void
    {
        $this->city = $city;
    }

    /**
     * Returns Region.
     */
    public function getRegion(): string
    {
        return $this->region;
    }

    /**
     * Sets Region.
     *
     * @required
     * @maps region
     */
    public function setRegion(string $region): void
    {
        $this->region = $region;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['id_business']   = $this->idBusiness;
        $json['name']          = $this->name;
        $json['code']          = $this->code;
        $json['adress']        = $this->adress;
        $json['adress number'] = $this->adressNumber;
        $json['reference']     = $this->reference;
        $json['city']          = $this->city;
        $json['region']        = $this->region;

        return $json;
    }
}
