<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib\Models;

class DELETEREQUEST implements \JsonSerializable
{
    /**
     * @var int
     */
    private $idBusiness;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $code;

    /**
     * @var string
     */
    private $adress;

    /**
     * @var string
     */
    private $adressNumber;

    /**
     * @var string
     */
    private $reference;

    /**
     * @var string
     */
    private $city;

    /**
     * @var string
     */
    private $region;

    /**
     * @var string
     */
    private $country;

    /**
     * @var int
     */
    private $idContact;

    /**
     * @var string
     */
    private $idCreator;

    /**
     * @var string
     */
    private $dateUp;

    /**
     * @var string|null
     */
    private $dateDown;

    /**
     * @var string
     */
    private $dateLastUpdate;

    /**
     * @param int $idBusiness
     * @param string $name
     * @param string $code
     * @param string $adress
     * @param string $adressNumber
     * @param string $reference
     * @param string $city
     * @param string $region
     * @param string $country
     * @param int $idContact
     * @param string $idCreator
     * @param string $dateUp
     * @param string $dateLastUpdate
     */
    public function __construct(
        int $idBusiness,
        string $name,
        string $code,
        string $adress,
        string $adressNumber,
        string $reference,
        string $city,
        string $region,
        string $country,
        int $idContact,
        string $idCreator,
        string $dateUp,
        string $dateLastUpdate
    ) {
        $this->idBusiness = $idBusiness;
        $this->name = $name;
        $this->code = $code;
        $this->adress = $adress;
        $this->adressNumber = $adressNumber;
        $this->reference = $reference;
        $this->city = $city;
        $this->region = $region;
        $this->country = $country;
        $this->idContact = $idContact;
        $this->idCreator = $idCreator;
        $this->dateUp = $dateUp;
        $this->dateLastUpdate = $dateLastUpdate;
    }

    /**
     * Returns Id Business.
     */
    public function getIdBusiness(): int
    {
        return $this->idBusiness;
    }

    /**
     * Sets Id Business.
     *
     * @required
     * @maps id_business
     */
    public function setIdBusiness(int $idBusiness): void
    {
        $this->idBusiness = $idBusiness;
    }

    /**
     * Returns Name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Code.
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * Sets Code.
     *
     * @required
     * @maps code
     */
    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    /**
     * Returns Adress.
     */
    public function getAdress(): string
    {
        return $this->adress;
    }

    /**
     * Sets Adress.
     *
     * @required
     * @maps adress
     */
    public function setAdress(string $adress): void
    {
        $this->adress = $adress;
    }

    /**
     * Returns Adress Number.
     */
    public function getAdressNumber(): string
    {
        return $this->adressNumber;
    }

    /**
     * Sets Adress Number.
     *
     * @required
     * @maps adress_number
     */
    public function setAdressNumber(string $adressNumber): void
    {
        $this->adressNumber = $adressNumber;
    }

    /**
     * Returns Reference.
     */
    public function getReference(): string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     *
     * @required
     * @maps reference
     */
    public function setReference(string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns City.
     */
    public function getCity(): string
    {
        return $this->city;
    }

    /**
     * Sets City.
     *
     * @required
     * @maps city
     */
    public function setCity(string $city): void
    {
        $this->city = $city;
    }

    /**
     * Returns Region.
     */
    public function getRegion(): string
    {
        return $this->region;
    }

    /**
     * Sets Region.
     *
     * @required
     * @maps region
     */
    public function setRegion(string $region): void
    {
        $this->region = $region;
    }

    /**
     * Returns Country.
     */
    public function getCountry(): string
    {
        return $this->country;
    }

    /**
     * Sets Country.
     *
     * @required
     * @maps country
     */
    public function setCountry(string $country): void
    {
        $this->country = $country;
    }

    /**
     * Returns Id Contact.
     */
    public function getIdContact(): int
    {
        return $this->idContact;
    }

    /**
     * Sets Id Contact.
     *
     * @required
     * @maps id_contact
     */
    public function setIdContact(int $idContact): void
    {
        $this->idContact = $idContact;
    }

    /**
     * Returns Id Creator.
     */
    public function getIdCreator(): string
    {
        return $this->idCreator;
    }

    /**
     * Sets Id Creator.
     *
     * @required
     * @maps id_creator
     */
    public function setIdCreator(string $idCreator): void
    {
        $this->idCreator = $idCreator;
    }

    /**
     * Returns Date Up.
     */
    public function getDateUp(): string
    {
        return $this->dateUp;
    }

    /**
     * Sets Date Up.
     *
     * @required
     * @maps date_up
     */
    public function setDateUp(string $dateUp): void
    {
        $this->dateUp = $dateUp;
    }

    /**
     * Returns Date Down.
     */
    public function getDateDown(): ?string
    {
        return $this->dateDown;
    }

    /**
     * Sets Date Down.
     *
     * @maps date_down
     */
    public function setDateDown(?string $dateDown): void
    {
        $this->dateDown = $dateDown;
    }

    /**
     * Returns Date Last Update.
     */
    public function getDateLastUpdate(): string
    {
        return $this->dateLastUpdate;
    }

    /**
     * Sets Date Last Update.
     *
     * @required
     * @maps date_last_update
     */
    public function setDateLastUpdate(string $dateLastUpdate): void
    {
        $this->dateLastUpdate = $dateLastUpdate;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['id_business']      = $this->idBusiness;
        $json['name']             = $this->name;
        $json['code']             = $this->code;
        $json['adress']           = $this->adress;
        $json['adress_number']    = $this->adressNumber;
        $json['reference']        = $this->reference;
        $json['city']             = $this->city;
        $json['region']           = $this->region;
        $json['country']          = $this->country;
        $json['id_contact']       = $this->idContact;
        $json['id_creator']       = $this->idCreator;
        $json['date_up']          = $this->dateUp;
        $json['date_down']        = $this->dateDown;
        $json['date_last_update'] = $this->dateLastUpdate;

        return $json;
    }
}
