<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib\Models;

class ELIMINARITEMARETIROREQUEST implements \JsonSerializable
{
    /**
     * @var int
     */
    private $idRetirement;

    /**
     * @var string
     */
    private $idItem;

    /**
     * @param int $idRetirement
     * @param string $idItem
     */
    public function __construct(int $idRetirement, string $idItem)
    {
        $this->idRetirement = $idRetirement;
        $this->idItem = $idItem;
    }

    /**
     * Returns Id Retirement.
     */
    public function getIdRetirement(): int
    {
        return $this->idRetirement;
    }

    /**
     * Sets Id Retirement.
     *
     * @required
     * @maps id_retirement
     */
    public function setIdRetirement(int $idRetirement): void
    {
        $this->idRetirement = $idRetirement;
    }

    /**
     * Returns Id Item.
     */
    public function getIdItem(): string
    {
        return $this->idItem;
    }

    /**
     * Sets Id Item.
     *
     * @required
     * @maps id_item
     */
    public function setIdItem(string $idItem): void
    {
        $this->idItem = $idItem;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['id_retirement'] = $this->idRetirement;
        $json['id_item']       = $this->idItem;

        return $json;
    }
}
