<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib\Models;

class INGRESARITEMARETIROREQUEST implements \JsonSerializable
{
    /**
     * @var int
     */
    private $idRetirement;

    /**
     * @var string
     */
    private $label;

    /**
     * @param int $idRetirement
     * @param string $label
     */
    public function __construct(int $idRetirement, string $label)
    {
        $this->idRetirement = $idRetirement;
        $this->label = $label;
    }

    /**
     * Returns Id Retirement.
     */
    public function getIdRetirement(): int
    {
        return $this->idRetirement;
    }

    /**
     * Sets Id Retirement.
     *
     * @required
     * @maps id_retirement
     */
    public function setIdRetirement(int $idRetirement): void
    {
        $this->idRetirement = $idRetirement;
    }

    /**
     * Returns Label.
     */
    public function getLabel(): string
    {
        return $this->label;
    }

    /**
     * Sets Label.
     *
     * @required
     * @maps label
     */
    public function setLabel(string $label): void
    {
        $this->label = $label;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['id_retirement'] = $this->idRetirement;
        $json['label']         = $this->label;

        return $json;
    }
}
