<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib\Models;

class Item implements \JsonSerializable
{
    /**
     * @var string
     */
    private $identifier;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $qty;

    /**
     * @var string|null
     */
    private $link;

    /**
     * @var int|null
     */
    private $price;

    /**
     * @param string $identifier
     * @param string $name
     * @param string $qty
     */
    public function __construct(string $identifier, string $name, string $qty)
    {
        $this->identifier = $identifier;
        $this->name = $name;
        $this->qty = $qty;
    }

    /**
     * Returns Identifier.
     */
    public function getIdentifier(): string
    {
        return $this->identifier;
    }

    /**
     * Sets Identifier.
     *
     * @required
     * @maps identifier
     */
    public function setIdentifier(string $identifier): void
    {
        $this->identifier = $identifier;
    }

    /**
     * Returns Name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Qty.
     */
    public function getQty(): string
    {
        return $this->qty;
    }

    /**
     * Sets Qty.
     *
     * @required
     * @maps qty
     */
    public function setQty(string $qty): void
    {
        $this->qty = $qty;
    }

    /**
     * Returns Link.
     */
    public function getLink(): ?string
    {
        return $this->link;
    }

    /**
     * Sets Link.
     *
     * @maps link
     */
    public function setLink(?string $link): void
    {
        $this->link = $link;
    }

    /**
     * Returns Price.
     */
    public function getPrice(): ?int
    {
        return $this->price;
    }

    /**
     * Sets Price.
     *
     * @maps price
     */
    public function setPrice(?int $price): void
    {
        $this->price = $price;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['identifier'] = $this->identifier;
        $json['name']       = $this->name;
        $json['qty']        = $this->qty;
        if (isset($this->link)) {
            $json['link']   = $this->link;
        }
        if (isset($this->price)) {
            $json['price']  = $this->price;
        }

        return $json;
    }
}
