<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib\Models;

class Item1 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $identifier;

    /**
     * @var string
     */
    private $name;

    /**
     * @var int
     */
    private $quantity;

    /**
     * @param string $identifier
     * @param string $name
     * @param int $quantity
     */
    public function __construct(string $identifier, string $name, int $quantity)
    {
        $this->identifier = $identifier;
        $this->name = $name;
        $this->quantity = $quantity;
    }

    /**
     * Returns Identifier.
     */
    public function getIdentifier(): string
    {
        return $this->identifier;
    }

    /**
     * Sets Identifier.
     *
     * @required
     * @maps identifier
     */
    public function setIdentifier(string $identifier): void
    {
        $this->identifier = $identifier;
    }

    /**
     * Returns Name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Quantity.
     */
    public function getQuantity(): int
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     *
     * @required
     * @maps quantity
     */
    public function setQuantity(int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['identifier'] = $this->identifier;
        $json['name']       = $this->name;
        $json['quantity']   = $this->quantity;

        return $json;
    }
}
