<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib\Models;

class NotificationsOrderRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $resource;

    /**
     * @var string
     */
    private $userId;

    /**
     * @var string
     */
    private $topic;

    /**
     * @var string
     */
    private $applicationId;

    /**
     * @var string
     */
    private $attempts;

    /**
     * @var string
     */
    private $sent;

    /**
     * @var string
     */
    private $received;

    /**
     * @param string $resource
     * @param string $userId
     * @param string $topic
     * @param string $applicationId
     * @param string $attempts
     * @param string $sent
     * @param string $received
     */
    public function __construct(
        string $resource,
        string $userId,
        string $topic,
        string $applicationId,
        string $attempts,
        string $sent,
        string $received
    ) {
        $this->resource = $resource;
        $this->userId = $userId;
        $this->topic = $topic;
        $this->applicationId = $applicationId;
        $this->attempts = $attempts;
        $this->sent = $sent;
        $this->received = $received;
    }

    /**
     * Returns Resource.
     */
    public function getResource(): string
    {
        return $this->resource;
    }

    /**
     * Sets Resource.
     *
     * @required
     * @maps resource
     */
    public function setResource(string $resource): void
    {
        $this->resource = $resource;
    }

    /**
     * Returns User Id.
     */
    public function getUserId(): string
    {
        return $this->userId;
    }

    /**
     * Sets User Id.
     *
     * @required
     * @maps user_id
     */
    public function setUserId(string $userId): void
    {
        $this->userId = $userId;
    }

    /**
     * Returns Topic.
     */
    public function getTopic(): string
    {
        return $this->topic;
    }

    /**
     * Sets Topic.
     *
     * @required
     * @maps topic
     */
    public function setTopic(string $topic): void
    {
        $this->topic = $topic;
    }

    /**
     * Returns Application Id.
     */
    public function getApplicationId(): string
    {
        return $this->applicationId;
    }

    /**
     * Sets Application Id.
     *
     * @required
     * @maps application_id
     */
    public function setApplicationId(string $applicationId): void
    {
        $this->applicationId = $applicationId;
    }

    /**
     * Returns Attempts.
     */
    public function getAttempts(): string
    {
        return $this->attempts;
    }

    /**
     * Sets Attempts.
     *
     * @required
     * @maps attempts
     */
    public function setAttempts(string $attempts): void
    {
        $this->attempts = $attempts;
    }

    /**
     * Returns Sent.
     */
    public function getSent(): string
    {
        return $this->sent;
    }

    /**
     * Sets Sent.
     *
     * @required
     * @maps sent
     */
    public function setSent(string $sent): void
    {
        $this->sent = $sent;
    }

    /**
     * Returns Received.
     */
    public function getReceived(): string
    {
        return $this->received;
    }

    /**
     * Sets Received.
     *
     * @required
     * @maps received
     */
    public function setReceived(string $received): void
    {
        $this->received = $received;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['resource']       = $this->resource;
        $json['user_id']        = $this->userId;
        $json['topic']          = $this->topic;
        $json['application_id'] = $this->applicationId;
        $json['attempts']       = $this->attempts;
        $json['sent']           = $this->sent;
        $json['received']       = $this->received;

        return $json;
    }
}
