<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib\Models;

class Order implements \JsonSerializable
{
    /**
     * @var string
     */
    private $sizePackages;

    /**
     * @var int
     */
    private $amountSecure;

    /**
     * @var Item[]
     */
    private $items;

    /**
     * @param string $sizePackages
     * @param int $amountSecure
     * @param Item[] $items
     */
    public function __construct(string $sizePackages, int $amountSecure, array $items)
    {
        $this->sizePackages = $sizePackages;
        $this->amountSecure = $amountSecure;
        $this->items = $items;
    }

    /**
     * Returns Size Packages.
     */
    public function getSizePackages(): string
    {
        return $this->sizePackages;
    }

    /**
     * Sets Size Packages.
     *
     * @required
     * @maps size_packages
     */
    public function setSizePackages(string $sizePackages): void
    {
        $this->sizePackages = $sizePackages;
    }

    /**
     * Returns Amount Secure.
     */
    public function getAmountSecure(): int
    {
        return $this->amountSecure;
    }

    /**
     * Sets Amount Secure.
     *
     * @required
     * @maps amount_secure
     */
    public function setAmountSecure(int $amountSecure): void
    {
        $this->amountSecure = $amountSecure;
    }

    /**
     * Returns Items.
     *
     * @return Item[]
     */
    public function getItems(): array
    {
        return $this->items;
    }

    /**
     * Sets Items.
     *
     * @required
     * @maps items
     *
     * @param Item[] $items
     */
    public function setItems(array $items): void
    {
        $this->items = $items;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['size_packages'] = $this->sizePackages;
        $json['amount_secure'] = $this->amountSecure;
        $json['items']         = $this->items;

        return $json;
    }
}
