<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib\Models;

class Order1 implements \JsonSerializable
{
    /**
     * @var int
     */
    private $numberPackages;

    /**
     * @var string
     */
    private $sizePackages;

    /**
     * @var int
     */
    private $amountSecure;

    /**
     * @var Item1[]
     */
    private $items;

    /**
     * @param int $numberPackages
     * @param string $sizePackages
     * @param int $amountSecure
     * @param Item1[] $items
     */
    public function __construct(int $numberPackages, string $sizePackages, int $amountSecure, array $items)
    {
        $this->numberPackages = $numberPackages;
        $this->sizePackages = $sizePackages;
        $this->amountSecure = $amountSecure;
        $this->items = $items;
    }

    /**
     * Returns Number Packages.
     */
    public function getNumberPackages(): int
    {
        return $this->numberPackages;
    }

    /**
     * Sets Number Packages.
     *
     * @required
     * @maps number_packages
     */
    public function setNumberPackages(int $numberPackages): void
    {
        $this->numberPackages = $numberPackages;
    }

    /**
     * Returns Size Packages.
     */
    public function getSizePackages(): string
    {
        return $this->sizePackages;
    }

    /**
     * Sets Size Packages.
     *
     * @required
     * @maps size_packages
     */
    public function setSizePackages(string $sizePackages): void
    {
        $this->sizePackages = $sizePackages;
    }

    /**
     * Returns Amount Secure.
     */
    public function getAmountSecure(): int
    {
        return $this->amountSecure;
    }

    /**
     * Sets Amount Secure.
     *
     * @required
     * @maps amount_secure
     */
    public function setAmountSecure(int $amountSecure): void
    {
        $this->amountSecure = $amountSecure;
    }

    /**
     * Returns Items.
     *
     * @return Item1[]
     */
    public function getItems(): array
    {
        return $this->items;
    }

    /**
     * Sets Items.
     *
     * @required
     * @maps items
     *
     * @param Item1[] $items
     */
    public function setItems(array $items): void
    {
        $this->items = $items;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['number_packages'] = $this->numberPackages;
        $json['size_packages']   = $this->sizePackages;
        $json['amount_secure']   = $this->amountSecure;
        $json['items']           = $this->items;

        return $json;
    }
}
