<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib;

/**
 * Environments available for API
 */
class Environment
{
    public const SERVIDORES = 'Servidores';
}
