<?php

declare(strict_types=1);

/*
 * APIEXTERNALLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIEXTERNALLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const PRODUCCI_N = 'Producción';

    public const DESARROLLO = 'Desarrollo';
}
